# Setup
title: EJQS
url: https://ejqs.net
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  # - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Update (2025-11-05): UA-000000-0 format will not work.
# Universal Analytics was sunset on July 1, 2024.
# ---
# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: G-XXXXXXXXXX

# Specify the author for blog posts
author:
  name: Earlan Josh Q. Sabillano
  url: https://x.com/ejqs
  email: ejqs@ejqs.net

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about
